language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install -q testtools fixtures
  - python setup.py -q install

script:
  - python setup.py -q test
